#!/usr/bin/env bash
# Loop Bash Script, 30.05.26, ZeroK
# 01.06.26: added $@ for multiple args in input


# for loop
# $@ creates an array that stores n number of args
for word in "$@"; do
    echo "word is $word" 
done

# run this
# ./loop one apple two bananas three cantaloupes

# run this in terminal
# bash -n loop (checks for syntax errors)
# echo $? (returns 0 on successful execution of last command in terminal)
